### PR TITLE
TypeError: Cannot read property 'onPageChanged' of undefined Fix

### PR DESCRIPTION
**Pull request by AbdalrahmanHafez**

### CODE REVIEW

**Comment by andrew222651** [comment]
Is it necessary?

**Comment by AbdalrahmanHafez** [comment]
image
image

**Comment by AbdalrahmanHafez** [comment]
Chrome Version 85.0.4183.121
when loaded an error message "TypeError: Cannot read property 'onPageChanged' of undefined"
which as stated here **[stackoverflow.com/questions/25409679/cannot-read-property-onpagechanged-of-undefined](https://stackoverflow.com/questions/25409679/cannot-read-property-onpagechanged-of-undefined)**
needs this permission (declarativeContent)

**Comment by andrew222651** [comment]
Thank you. I've removed that code, please try it now.

**Pull request closed without merging**
